package pojos;
// Generated 24-feb-2024 18:38:27 by Hibernate Tools 4.3.1



/**
 * AlumnosAsignaturas generated by hbm2java
 */
public class AlumnosAsignaturas  implements java.io.Serializable {


     private Integer idAlumAsig;
     private Alumnos alumnos;
     private Asignaturas asignaturas;

    public AlumnosAsignaturas() {
    }

    public AlumnosAsignaturas(Alumnos alumnos, Asignaturas asignaturas) {
       this.alumnos = alumnos;
       this.asignaturas = asignaturas;
    }
   
    public Integer getIdAlumAsig() {
        return this.idAlumAsig;
    }
    
    public void setIdAlumAsig(Integer idAlumAsig) {
        this.idAlumAsig = idAlumAsig;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Asignaturas getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Asignaturas asignaturas) {
        this.asignaturas = asignaturas;
    }




}


