package pojos;
// Generated 09-feb-2024 2:11:34 by Hibernate Tools 4.3.1



/**
 * Anexos generated by hbm2java
 */
public class Anexos  implements java.io.Serializable {


     private Integer idAnexo;
     private String tutorPracticas;
     private String fechaInicio;
     private String fechaFin;
     private String idNecesidad;
     private String dniAlumno;
     private Boolean contratacion;
     private byte[] anexoDosUno;
     private byte[] anexoTres;
     private byte[] anexoCuatro;
     private byte[] anexoDosDos;
     private byte[] anexoOcho;

    public Anexos() {
    }

    public Anexos(String tutorPracticas, String fechaInicio, String fechaFin, String idNecesidad, String dniAlumno, Boolean contratacion, byte[] anexoDosUno, byte[] anexoTres, byte[] anexoCuatro, byte[] anexoDosDos, byte[] anexoOcho) {
       this.tutorPracticas = tutorPracticas;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.idNecesidad = idNecesidad;
       this.dniAlumno = dniAlumno;
       this.contratacion = contratacion;
       this.anexoDosUno = anexoDosUno;
       this.anexoTres = anexoTres;
       this.anexoCuatro = anexoCuatro;
       this.anexoDosDos = anexoDosDos;
       this.anexoOcho = anexoOcho;
    }
   
    public Integer getIdAnexo() {
        return this.idAnexo;
    }
    
    public void setIdAnexo(Integer idAnexo) {
        this.idAnexo = idAnexo;
    }
    public String getTutorPracticas() {
        return this.tutorPracticas;
    }
    
    public void setTutorPracticas(String tutorPracticas) {
        this.tutorPracticas = tutorPracticas;
    }
    public String getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public String getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getIdNecesidad() {
        return this.idNecesidad;
    }
    
    public void setIdNecesidad(String idNecesidad) {
        this.idNecesidad = idNecesidad;
    }
    public String getDniAlumno() {
        return this.dniAlumno;
    }
    
    public void setDniAlumno(String dniAlumno) {
        this.dniAlumno = dniAlumno;
    }
    public Boolean getContratacion() {
        return this.contratacion;
    }
    
    public void setContratacion(Boolean contratacion) {
        this.contratacion = contratacion;
    }
    public byte[] getAnexoDosUno() {
        return this.anexoDosUno;
    }
    
    public void setAnexoDosUno(byte[] anexoDosUno) {
        this.anexoDosUno = anexoDosUno;
    }
    public byte[] getAnexoTres() {
        return this.anexoTres;
    }
    
    public void setAnexoTres(byte[] anexoTres) {
        this.anexoTres = anexoTres;
    }
    public byte[] getAnexoCuatro() {
        return this.anexoCuatro;
    }
    
    public void setAnexoCuatro(byte[] anexoCuatro) {
        this.anexoCuatro = anexoCuatro;
    }
    public byte[] getAnexoDosDos() {
        return this.anexoDosDos;
    }
    
    public void setAnexoDosDos(byte[] anexoDosDos) {
        this.anexoDosDos = anexoDosDos;
    }
    public byte[] getAnexoOcho() {
        return this.anexoOcho;
    }
    
    public void setAnexoOcho(byte[] anexoOcho) {
        this.anexoOcho = anexoOcho;
    }




}


