package pojos;
// Generated 27-feb-2024 19:04:12 by Hibernate Tools 4.3.1



/**
 * Beep generated by hbm2java
 */
public class Beep  implements java.io.Serializable {


     private int idUsuario;
     private Login login;
     private String hashContrasena;
     private String salt;

    public Beep() {
    }

	
    public Beep(Login login) {
        this.login = login;
    }
    public Beep(Login login, String hashContrasena, String salt) {
       this.login = login;
       this.hashContrasena = hashContrasena;
       this.salt = salt;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public String getHashContrasena() {
        return this.hashContrasena;
    }
    
    public void setHashContrasena(String hashContrasena) {
        this.hashContrasena = hashContrasena;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }




}


