package pojos;
// Generated 17-feb-2024 19:37:18 by Hibernate Tools 4.3.1



/**
 * Convenio generated by hbm2java
 */
public class Convenio  implements java.io.Serializable {


     private int numConvenio;
     private Empresas empresas;
     private String idAnexo;
     private String nombreEmpresa;
     private String responsableFirma;
     private Integer cantAnexos;
     private byte[] anexoUnoConvenio;

    public Convenio() {
    }

	
    public Convenio(int numConvenio, byte[] anexoUnoConvenio) {
        this.numConvenio = numConvenio;
        this.anexoUnoConvenio = anexoUnoConvenio;
    }
    public Convenio(int numConvenio, Empresas empresas, String idAnexo, String nombreEmpresa, String responsableFirma, Integer cantAnexos, byte[] anexoUnoConvenio) {
       this.numConvenio = numConvenio;
       this.empresas = empresas;
       this.idAnexo = idAnexo;
       this.nombreEmpresa = nombreEmpresa;
       this.responsableFirma = responsableFirma;
       this.cantAnexos = cantAnexos;
       this.anexoUnoConvenio = anexoUnoConvenio;
    }
   
    public int getNumConvenio() {
        return this.numConvenio;
    }
    
    public void setNumConvenio(int numConvenio) {
        this.numConvenio = numConvenio;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getIdAnexo() {
        return this.idAnexo;
    }
    
    public void setIdAnexo(String idAnexo) {
        this.idAnexo = idAnexo;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getResponsableFirma() {
        return this.responsableFirma;
    }
    
    public void setResponsableFirma(String responsableFirma) {
        this.responsableFirma = responsableFirma;
    }
    public Integer getCantAnexos() {
        return this.cantAnexos;
    }
    
    public void setCantAnexos(Integer cantAnexos) {
        this.cantAnexos = cantAnexos;
    }
    public byte[] getAnexoUnoConvenio() {
        return this.anexoUnoConvenio;
    }
    
    public void setAnexoUnoConvenio(byte[] anexoUnoConvenio) {
        this.anexoUnoConvenio = anexoUnoConvenio;
    }




}


