package pojos;
// Generated 28-feb-2024 17:10:15 by Hibernate Tools 4.3.1

/**
 * Convenio generated by hbm2java
 */
public class Convenio implements java.io.Serializable {

    private Integer idConvenio;
    private Empresas empresas;
    private int numConvenio;
    private String nombreEmpresa;
    private String responsableFirma;
    private Integer cantAnexos;
    private byte[] anexoUnoConvenio;

    public Convenio() {
    }

    public Convenio(Empresas empresas, int numConvenio) {
        this.empresas = empresas;
        this.numConvenio = numConvenio;
    }

    public Convenio(Integer idConvenio, Empresas empresas, int numConvenio, String nombreEmpresa, String responsableFirma, Integer cantAnexos, byte[] anexoUnoConvenio) {
        this.idConvenio = idConvenio;
        this.empresas = empresas;
        this.numConvenio = numConvenio;
        this.nombreEmpresa = nombreEmpresa;
        this.responsableFirma = responsableFirma;
        this.cantAnexos = cantAnexos;
        this.anexoUnoConvenio = anexoUnoConvenio;
    }

    public Convenio(Empresas empresas, int numConvenio, String nombreEmpresa, String responsableFirma, Integer cantAnexos, byte[] anexoUnoConvenio) {
        this.empresas = empresas;
        this.numConvenio = numConvenio;
        this.nombreEmpresa = nombreEmpresa;
        this.responsableFirma = responsableFirma;
        this.cantAnexos = cantAnexos;
        this.anexoUnoConvenio = anexoUnoConvenio;
    }

    public Integer getIdConvenio() {
        return this.idConvenio;
    }

    public void setIdConvenio(Integer idConvenio) {
        this.idConvenio = idConvenio;
    }

    public Empresas getEmpresas() {
        return this.empresas;
    }

    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }

    public int getNumConvenio() {
        return this.numConvenio;
    }

    public void setNumConvenio(int numConvenio) {
        this.numConvenio = numConvenio;
    }

    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }

    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }

    public String getResponsableFirma() {
        return this.responsableFirma;
    }

    public void setResponsableFirma(String responsableFirma) {
        this.responsableFirma = responsableFirma;
    }

    public Integer getCantAnexos() {
        return this.cantAnexos;
    }

    public void setCantAnexos(Integer cantAnexos) {
        this.cantAnexos = cantAnexos;
    }

    public byte[] getAnexoUnoConvenio() {
        return this.anexoUnoConvenio;
    }

    public void setAnexoUnoConvenio(byte[] anexoUnoConvenio) {
        this.anexoUnoConvenio = anexoUnoConvenio;
    }

}
