package pojos;
// Generated 14-feb-2024 20:16:34 by Hibernate Tools 4.3.1



/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private String cifEmpresa;
     private String nombreEmpresa;
     private String direccion;
     private String telefono;
     private String owner;
     private String tutorPracticas;
     private String responsableContratacion;

    public Empresas() {
    }

	
    public Empresas(String cifEmpresa) {
        this.cifEmpresa = cifEmpresa;
    }
    public Empresas(String cifEmpresa, String nombreEmpresa, String direccion, String telefono, String owner, String tutorPracticas, String responsableContratacion) {
       this.cifEmpresa = cifEmpresa;
       this.nombreEmpresa = nombreEmpresa;
       this.direccion = direccion;
       this.telefono = telefono;
       this.owner = owner;
       this.tutorPracticas = tutorPracticas;
       this.responsableContratacion = responsableContratacion;
    }
   
    public String getCifEmpresa() {
        return this.cifEmpresa;
    }
    
    public void setCifEmpresa(String cifEmpresa) {
        this.cifEmpresa = cifEmpresa;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getTutorPracticas() {
        return this.tutorPracticas;
    }
    
    public void setTutorPracticas(String tutorPracticas) {
        this.tutorPracticas = tutorPracticas;
    }
    public String getResponsableContratacion() {
        return this.responsableContratacion;
    }
    
    public void setResponsableContratacion(String responsableContratacion) {
        this.responsableContratacion = responsableContratacion;
    }




}


