package pojos;
// Generated 27-feb-2024 2:36:57 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Necesidad generated by hbm2java
 */
public class Necesidad implements java.io.Serializable {

    private Integer idNecesidad;
    private Empresas empresas;
    private String cicloNecesidad;
    private Integer dam;
    private Integer daw;
    private Integer asir;
    private Integer mark;
    private Integer fin;
    private Set anexoses = new HashSet(0);

    public Necesidad() {
    }

    public Necesidad(Integer idNecesidad) {
        this.idNecesidad = idNecesidad;
    }

    public Necesidad(Empresas empresas, String cicloNecesidad, Integer dam, Integer daw, Integer asir, Integer mark, Integer fin, Set anexoses) {
        this.empresas = empresas;
        this.cicloNecesidad = cicloNecesidad;
        this.dam = dam;
        this.daw = daw;
        this.asir = asir;
        this.mark = mark;
        this.fin = fin;
        this.anexoses = anexoses;
    }

    public Integer getIdNecesidad() {
        return this.idNecesidad;
    }

    public void setIdNecesidad(Integer idNecesidad) {
        this.idNecesidad = idNecesidad;
    }

    public Empresas getEmpresas() {
        return this.empresas;
    }

    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }

    public String getCicloNecesidad() {
        return this.cicloNecesidad;
    }

    public void setCicloNecesidad(String cicloNecesidad) {
        this.cicloNecesidad = cicloNecesidad;
    }

    public Integer getDam() {
        return this.dam;
    }

    public void setDam(Integer dam) {
        this.dam = dam;
    }

    public Integer getDaw() {
        return this.daw;
    }

    public void setDaw(Integer daw) {
        this.daw = daw;
    }

    public Integer getAsir() {
        return this.asir;
    }

    public void setAsir(Integer asir) {
        this.asir = asir;
    }

    public Integer getMark() {
        return this.mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    public Integer getFin() {
        return this.fin;
    }

    public void setFin(Integer fin) {
        this.fin = fin;
    }

    public Set getAnexoses() {
        return this.anexoses;
    }

    public void setAnexoses(Set anexoses) {
        this.anexoses = anexoses;
    }

}
