package pojos;
// Generated 28-feb-2024 17:10:15 by Hibernate Tools 4.3.1



/**
 * Practicas generated by hbm2java
 */
public class Practicas  implements java.io.Serializable {


     private Integer idPractica;
     private Alumnos alumnos;
     private Anexos anexos;
     private Empresas empresas;
     private byte[] informeSeguimiento;
     private byte[] informeFinal;
     private String horarioEntrada;
     private String horarioSalida;

    public Practicas() {
    }

	
    public Practicas(String horarioEntrada, String horarioSalida) {
        this.horarioEntrada = horarioEntrada;
        this.horarioSalida = horarioSalida;
    }
    public Practicas(Alumnos alumnos, Anexos anexos, Empresas empresas, byte[] informeSeguimiento, byte[] informeFinal, String horarioEntrada, String horarioSalida) {
       this.alumnos = alumnos;
       this.anexos = anexos;
       this.empresas = empresas;
       this.informeSeguimiento = informeSeguimiento;
       this.informeFinal = informeFinal;
       this.horarioEntrada = horarioEntrada;
       this.horarioSalida = horarioSalida;
    }
   
    public Integer getIdPractica() {
        return this.idPractica;
    }
    
    public void setIdPractica(Integer idPractica) {
        this.idPractica = idPractica;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Anexos getAnexos() {
        return this.anexos;
    }
    
    public void setAnexos(Anexos anexos) {
        this.anexos = anexos;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public byte[] getInformeSeguimiento() {
        return this.informeSeguimiento;
    }
    
    public void setInformeSeguimiento(byte[] informeSeguimiento) {
        this.informeSeguimiento = informeSeguimiento;
    }
    public byte[] getInformeFinal() {
        return this.informeFinal;
    }
    
    public void setInformeFinal(byte[] informeFinal) {
        this.informeFinal = informeFinal;
    }
    public String getHorarioEntrada() {
        return this.horarioEntrada;
    }
    
    public void setHorarioEntrada(String horarioEntrada) {
        this.horarioEntrada = horarioEntrada;
    }
    public String getHorarioSalida() {
        return this.horarioSalida;
    }
    
    public void setHorarioSalida(String horarioSalida) {
        this.horarioSalida = horarioSalida;
    }




}


